version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce-sql-test
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password123
    ports:
      - "1433:1433"

  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis-test
    ports:
      - "6379:6379"